In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import font_manager,rc
import matplotlib.pyplot as plt
rc('font',family='AppleGothic')

In [2]:
df =pd.read_excel('datascience.xlsx',index_col=0)
df1=pd.read_excel('datascience.xlsx',sheet_name=1,index_col=0)

In [3]:
df

,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
소비자물가,2.8,2.9,4.0,2.2,1.3,1.3,0.7,1.0,1.9,1.5,0.4,0.5,2.5,5.1
농축수산물,6.4,10.0,9.2,3.1,-0.6,-2.7,2.0,3.8,5.5,3.7,-1.7,6.7,8.7,3.8
공업제품,2.5,3.2,4.9,2.8,0.9,1.3,-0.2,-0.5,1.4,1.3,-0.2,-0.2,2.3,6.9
집세,1.6,1.9,4.0,4.2,2.7,2.3,2.5,1.9,1.6,0.6,-0.1,0.2,1.4,1.9
공공서비스,2.0,1.2,-0.4,0.5,0.7,0.7,1.2,1.5,1.0,0.2,-0.5,-1.9,1.0,0.8
개인서비스,2.8,2.2,3.7,1.1,1.6,1.7,1.9,2.7,2.5,2.5,1.9,1.2,2.6,5.4
근원물가,3.6,1.8,3.2,1.7,1.6,2.0,2.2,1.6,1.5,1.2,0.9,0.7,1.8,4.1
생활물가,2.1,3.4,4.4,1.7,0.7,0.8,-0.2,0.7,2.5,1.6,0.2,0.4,3.2,6.0

In [4]:
df1.T.mean()

소비자심리지수    101.808333
dtype: float64

In [5]:
df1

,200901월,200902월,200903월,200904월,200905월,200906월,200907월,200908월,200909월,200910월,...,202203월,202204월,202205월,202206월,202207월,202208월,202209월,202210월,202211월,202212월
소비자심리지수,84.0,85.0,84.0,98.0,105.0,106.0,109.0,114.0,114.0,117.0,...,103.5,104.1,102.9,96.7,86.3,89.0,91.6,89.0,86.7,90.2

In [6]:
df1 = df1.rename(columns=lambda x: str(x)[:4])
year=set(df1.columns)
year_list=[]
for i in year:
    year_list.append(i)
year_list=sorted(year_list)

In [7]:
mean_list=[]
for i in year_list:
    mean_list.append(df1[i].T.mean())
#저거 연도별 ㅕㅇ균 내고싶음

In [8]:
mean=pd.DataFrame(mean_list,index=year_list)
mean.T

,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
소비자심리지수,103.5,112.333333,102.25,100.333333,103.416667,105.916667,102.416667,99.491667,105.316667,104.0,99.116667,88.316667,103.241667,95.666667

In [9]:
df

,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
소비자물가,2.8,2.9,4.0,2.2,1.3,1.3,0.7,1.0,1.9,1.5,0.4,0.5,2.5,5.1
농축수산물,6.4,10.0,9.2,3.1,-0.6,-2.7,2.0,3.8,5.5,3.7,-1.7,6.7,8.7,3.8
공업제품,2.5,3.2,4.9,2.8,0.9,1.3,-0.2,-0.5,1.4,1.3,-0.2,-0.2,2.3,6.9
집세,1.6,1.9,4.0,4.2,2.7,2.3,2.5,1.9,1.6,0.6,-0.1,0.2,1.4,1.9
공공서비스,2.0,1.2,-0.4,0.5,0.7,0.7,1.2,1.5,1.0,0.2,-0.5,-1.9,1.0,0.8
개인서비스,2.8,2.2,3.7,1.1,1.6,1.7,1.9,2.7,2.5,2.5,1.9,1.2,2.6,5.4
근원물가,3.6,1.8,3.2,1.7,1.6,2.0,2.2,1.6,1.5,1.2,0.9,0.7,1.8,4.1
생활물가,2.1,3.4,4.4,1.7,0.7,0.8,-0.2,0.7,2.5,1.6,0.2,0.4,3.2,6.0

In [10]:
df2=pd.concat([df,mean.T])
df2=df2.T
df2

      소비자물가  농축수산물  공업제품   집세  공공서비스  개인서비스  근원물가  생활물가     소비자심리지수
2009    2.8    6.4   2.5  1.6    2.0    2.8   3.6   2.1  103.500000
2010    2.9   10.0   3.2  1.9    1.2    2.2   1.8   3.4  112.333333
2011    4.0    9.2   4.9  4.0   -0.4    3.7   3.2   4.4  102.250000
2012    2.2    3.1   2.8  4.2    0.5    1.1   1.7   1.7  100.333333
2013    1.3   -0.6   0.9  2.7    0.7    1.6   1.6   0.7  103.416667
2014    1.3   -2.7   1.3  2.3    0.7    1.7   2.0   0.8  105.916667
2015    0.7    2.0  -0.2  2.5    1.2    1.9   2.2  -0.2  102.416667
2016    1.0    3.8  -0.5  1.9    1.5    2.7   1.6   0.7   99.491667
2017    1.9    5.5   1.4  1.6    1.0    2.5   1.5   2.5  105.316667
2018    1.5    3.7   1.3  0.6    0.2    2.5   1.2   1.6  104.000000
2019    0.4   -1.7  -0.2 -0.1   -0.5    1.9   0.9   0.2   99.116667
2020    0.5    6.7  -0.2  0.2   -1.9    1.2   0.7   0.4   88.316667
2021    2.5    8.7   2.3  1.4    1.0    2.6   1.8   3.2  103.241667
2022    5.1    3.8   6.9  1.9    0.8    5.4   4.1   6.0   95.666667

In [11]:
mean = df2.mean()
std = df2.std()
normalized_data = (df2 - mean) / std
normalized_data
# Min-Max Scaling
df_norm = (df2 - df2.min()) / (df2.max() - df2.min())

# 결과 출력

         소비자물가     농축수산물      공업제품        집세     공공서비스     개인서비스      근원물가  \
2009  0.510638  0.716535  0.405405  0.395349  1.000000  0.395349  0.852941
2010  0.531915  1.000000  0.500000  0.465116  0.794872  0.255814  0.323529
2011  0.765957  0.937008  0.729730  0.953488  0.384615  0.604651  0.735294
2012  0.382979  0.456693  0.445946  1.000000  0.615385  0.000000  0.294118
2013  0.191489  0.165354  0.189189  0.651163  0.666667  0.116279  0.264706
2014  0.191489  0.000000  0.243243  0.558140  0.666667  0.139535  0.382353
2015  0.063830  0.370079  0.040541  0.604651  0.794872  0.186047  0.441176
2016  0.127660  0.511811  0.000000  0.465116  0.871795  0.372093  0.264706
2017  0.319149  0.645669  0.256757  0.395349  0.743590  0.325581  0.235294
2018  0.234043  0.503937  0.243243  0.162791  0.538462  0.325581  0.147059
2019  0.000000  0.078740  0.040541  0.000000  0.358974  0.186047  0.058824
2020  0.021277  0.740157  0.040541  0.069767  0.000000  0.023256  0.000000
2021  0.446809  0.897638  0.378378  0.348837  0.743590  0.348837  0.323529
2022  1.000000  0.511811  1.000000  0.465116  0.692308  1.000000  1.000000

          생활물가   소비자심리지수
2009  0.370968  0.632200
2010  0.580645  1.000000
2011  0.741935  0.580153
2012  0.306452  0.500347
2013  0.145161  0.628730
2014  0.161290  0.732824
2015  0.000000  0.587092
2016  0.145161  0.465302
2017  0.435484  0.707842
2018  0.290323  0.653019
2019  0.064516  0.449688
2020  0.096774  0.000000
2021  0.548387  0.621443
2022  1.000000  0.306037

In [13]:
df_norm

,소비자물가,농축수산물,공업제품,집세,공공서비스,개인서비스,근원물가,생활물가,소비자심리지수
2009,0.510638,0.716535,0.405405,0.395349,1.000000,0.395349,0.852941,0.370968,0.632200
2010,0.531915,1.000000,0.500000,0.465116,0.794872,0.255814,0.323529,0.580645,1.000000
2011,0.765957,0.937008,0.729730,0.953488,0.384615,0.604651,0.735294,0.741935,0.580153
2012,0.382979,0.456693,0.445946,1.000000,0.615385,0.000000,0.294118,0.306452,0.500347
2013,0.191489,0.165354,0.189189,0.651163,0.666667,0.116279,0.264706,0.145161,0.628730
2014,0.191489,0.000000,0.243243,0.558140,0.666667,0.139535,0.382353,0.161290,0.732824
2015,0.063830,0.370079,0.040541,0.604651,0.794872,0.186047,0.441176,0.000000,0.587092
2016,0.127660,0.511811,0.000000,0.465116,0.871795,0.372093,0.264706,0.145161,0.465302
2017,0.319149,0.645669,0.256757,0.395349,0.743590,0.325581,0.235294,0.435484,0.707842
2018,0.234043,0.503937,0.243243,0.162791,0.538462,0.325581,0.147059,0.290323,0.653019
2019,0.000000,0.078740,0.040541,0.000000,0.358974,0.186047,0.058824,0.064516,0.449688
2020,0.021277,0.740157,0.040541,0.069767,0.000000,0.023256,0.000000,0.096774,0.000000
2021,0.446809,0.897638,0.378378,0.348837,0.743590,0.348837,0.323529,0.548387,0.621443
2022,1.000000,0.511811,1.000000,0.465116,0.692308,1.000000,1.000000,1.000000,0.306037

In [19]:
correlations = df_norm.corr()['소비자심리지수']
print(correlations)

소비자물가      0.141961
농축수산물      0.094845
공업제품       0.104663
집세         0.273830
공공서비스      0.629769
개인서비스     -0.052806
근원물가       0.082419
생활물가       0.122996
소비자심리지수    1.000000
Name: 소비자심리지수, dtype: float64

In [21]:
# 각 열과 소비자 심리 지수 간의 가중 상관관계 계산
weighted_corr = df_norm.corrwith(df_norm['소비자심리지수'])

# 결과 출력
print(weighted_corr)

소비자물가      0.141961
농축수산물      0.094845
공업제품       0.104663
집세         0.273830
공공서비스      0.629769
개인서비스     -0.052806
근원물가       0.082419
생활물가       0.122996
소비자심리지수    1.000000
dtype: float64