In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib
from matplotlib import pyplot as plt
import os
from sklearn.cluster import KMeans

In [6]:
import platform
platform.platform()

pwd = os.getcwd()
pwd

'/Users/songsiho/Desktop/4/data_science/project/project/dataset'

In [41]:
matplotlib.rcParams['font.family']='AppleGothic'

In [42]:
total_sales_df=pd.read_csv('/Users/songsiho/Desktop/4/data_science/project/project/dataset/total_sales.csv',encoding='cp949')

In [43]:
total_sales_df=total_sales_df.loc[0:35]

In [45]:
total_sales_df.head()

,계정항목별,금융기관 유형코드별,2020.02,2020.03,2020.04,2020.05,2020.06,2020.07,2020.08,2020.09,...,2022.05,2022.06,2022.07,2022.08,2022.09,2022.10,2022.11,2022.12,2023.01,2023.02
0,전체 이용건수 (천건),합계,1103517,1124803,1129783,1226171,1240145,1254766,1243776,1188972,...,1500236,1443682,1486379,1518932,1426030,1506483,1455878,1450646,1391410,1321301
1,전체 이용건수 (천건),은행계,715030,729919,733955,796934,808651,815257,803354,769364,...,946066,909641,932080,957206,897733,944192,916559,909106,872798,829915
2,전체 이용건수 (천건),비은행계,388487,394884,395828,429237,431494,439509,440422,419608,...,554170,534041,554300,561726,528297,562292,539319,541540,518612,491386
3,개인 이용건수 (천건),합계,1017502,1040816,1043333,1139001,1147299,1153958,1152809,1096561,...,1390201,1334610,1373501,1411083,1321027,1397117,1345037,1339386,1293863,1221100
4,개인 이용건수 (천건),은행계,637529,653511,655435,717706,724429,723820,720411,685234,...,847255,811745,831096,860514,803939,846405,817824,809984,785832,741195

In [44]:
total_sales_df_total=total_sales_df[total_sales_df['금융기관 유형코드별']=='합계']

KeyError: '금융기관유형코드별'

In [34]:
total_sales_df.index=total_sales_df['계정항목별']

In [26]:
total_sales_df

,계정항목별,금융기관 유형코드별,2020.02,2020.03,2020.04,2020.05,2020.06,2020.07,2020.08,2020.09,...,2022.05,2022.06,2022.07,2022.08,2022.09,2022.10,2022.11,2022.12,2023.01,2023.02
계정항목별,,,,,,,,,,,,,,,,,,,,,
전체 이용건수 (천건),전체 이용건수 (천건),합계,1103517,1124803,1129783,1226171,1240145,1254766,1243776,1188972,...,1500236,1443682,1486379,1518932,1426030,1506483,1455878,1450646,1391410,1321301
전체 이용건수 (천건),전체 이용건수 (천건),은행계,715030,729919,733955,796934,808651,815257,803354,769364,...,946066,909641,932080,957206,897733,944192,916559,909106,872798,829915
전체 이용건수 (천건),전체 이용건수 (천건),비은행계,388487,394884,395828,429237,431494,439509,440422,419608,...,554170,534041,554300,561726,528297,562292,539319,541540,518612,491386
개인 이용건수 (천건),개인 이용건수 (천건),합계,1017502,1040816,1043333,1139001,1147299,1153958,1152809,1096561,...,1390201,1334610,1373501,1411083,1321027,1397117,1345037,1339386,1293863,1221100
개인 이용건수 (천건),개인 이용건수 (천건),은행계,637529,653511,655435,717706,724429,723820,720411,685234,...,847255,811745,831096,860514,803939,846405,817824,809984,785832,741195
개인 이용건수 (천건),개인 이용건수 (천건),비은행계,379973,387305,387898,421295,422869,430138,432397,411327,...,542946,522864,542405,550570,517088,550712,527213,529402,508031,479905
개인 일반구매 이용건수 (천건),개인 일반구매 이용건수 (천건),합계,981542,1002266,1006283,1101262,1109106,1114504,1114578,1056265,...,1343174,1290455,1328767,1365658,1275931,1349002,1297870,1292104,1248652,1180583
개인 일반구매 이용건수 (천건),개인 일반구매 이용건수 (천건),은행계,616181,630677,633754,695844,702562,701301,698739,662215,...,821688,787810,806903,835821,779254,820456,792142,783602,760994,718895
개인 일반구매 이용건수 (천건),개인 일반구매 이용건수 (천건),비은행계,365361,371590,372529,405417,406544,413203,415839,394050,...,521485,502645,521863,529836,496676,528546,505727,508502,487658,461688
개인 할부구매 이용건수 (천건),개인 할부구매 이용건수 (천건),합계,30056,32621,31848,32302,32863,34080,32952,35276,...,41982,39434,39956,40450,40219,42965,42086,42169,40345,35876
개인 할부구매 이용건수 (천건),개인 할부구매 이용건수 (천건),은행계,17394,18851,18209,18231,18295,18927,18161,19671,...,22254,20842,21092,21414,21476,22558,22314,23012,21605,19234
개인 할부구매 이용건수 (천건),개인 할부구매 이용건수 (천건),비은행계,12662,13770,13640,14071,14568,15154,14791,15605,...,19728,18593,18864,19036,18743,20407,19773,19157,18740,16642
개인 현금서비스 이용건수 (천건),개인 현금서비스 이용건수 (천건),합계,5903,5929,5202,5437,5329,5374,5279,5020,...,5045,4721,4779,4976,4878,5149,5081,5114,4866,4641
개인 현금서비스 이용건수 (천건),개인 현금서비스 이용건수 (천건),은행계,3953,3983,3473,3630,3572,3593,3511,3348,...,3313,3093,3101,3278,3209,3390,3368,3370,3233,3067
개인 현금서비스 이용건수 (천건),개인 현금서비스 이용건수 (천건),비은행계,1950,1946,1729,1807,1757,1781,1768,1672,...,1732,1627,1677,1697,1669,1759,1713,1744,1633,1574
법인 이용건수 (천건),법인 이용건수 (천건),합계,86016,83987,86450,87169,92846,100808,90967,92411,...,110035,109072,112878,107849,105003,109366,110841,111260,97547,100201
법인 이용건수 (천건),법인 이용건수 (천건),은행계,77502,76408,78520,79228,84222,91437,82942,84130,...,98811,97896,100983,96693,93794,97787,98735,99123,86966,88720
법인 이용건수 (천건),법인 이용건수 (천건),비은행계,8514,7579,7930,7941,8625,9371,8025,8281,...,11224,11177,11895,11156,11209,11580,12106,12137,10580,11481
전체 이용금액 (백만원),전체 이용금액 (백만원),합계,59686650,58844315,60385644,65011734,64039367,66802467,64447280,66934921,...,84787819,79395263,82207664,81112499,82343480,83378034,80536440,84793096,80255412,75947115
전체 이용금액 (백만원),전체 이용금액 (백만원),은행계,36930450,36751362,37976954,40557332,39319491,42004252,40062493,41695450,...,50329676,47945812,49926556,48684844,49886716,50001634,49024756,51765138,48447519,45198690
전체 이용금액 (백만원),전체 이용금액 (백만원),비은행계,22756200,22092953,22408690,24454401,24719875,24798215,24384787,25239471,...,34458142,31449451,32281108,32427655,32456764,33376400,31511685,33027957,31807894,30748425
개인 이용금액 (백만원),개인 이용금액 (백만원),합계,47456178,47842988,48165421,52246516,51676859,53124206,51785217,52354938,...,64933419,62871749,65806421,65000559,63882023,66388297,65224427,66883892,65249137,61364252
개인 이용금액 (백만원),개인 이용금액 (백만원),은행계,29330703,29375367,29577082,31890291,31207858,32151590,31348820,31630833,...,37768177,36780090,38617081,37856347,37277444,38416000,38319637,39060772,37827385,35580145
개인 이용금액 (백만원),개인 이용금액 (백만원),비은행계,18125475,18467621,18588339,20356226,20469001,20972616,20436397,20724105,...,27165243,26091659,27189340,27144212,26604579,27972297,26904790,27823120,27421752,25784107
개인 일반구매 이용금액 (백만원),개인 일반구매 이용금액 (백만원),합계,33470170,33537215,34256743,37940563,37286494,37623749,37098223,37172476,...,47523800,45899455,47711654,47700792,46248330,47820124,47497499,48896098,47712025,45244797
개인 일반구매 이용금액 (백만원),개인 일반구매 이용금액 (백만원),은행계,20943289,20878043,21383681,23536046,22935762,23150459,22884542,22838479,...,28124496,27331522,28406351,28226461,27323759,28064113,28224052,28540066,27948745,26436111
개인 일반구매 이용금액 (백만원),개인 일반구매 이용금액 (백만원),비은행계,12526881,12659172,12873062,14404517,14350733,14473290,14213681,14333997,...,19399304,18567934,19305303,19474330,18924571,19756011,19273447,20356032,19763280,18808686
개인 할부구매 이용금액 (백만원),개인 할부구매 이용금액 (백만원),합계,9163416,9299170,9545731,9813374,9963721,11059844,10200371,10828941,...,12509073,12223319,13363974,12379037,12715849,13595914,12778240,13042335,12904639,11645579
개인 할부구매 이용금액 (백만원),개인 할부구매 이용금액 (백만원),은행계,5236116,5220296,5348549,5419646,5382636,6102044,5560255,5975573,...,6501601,6411873,7216366,6474671,6781132,7129432,6852446,7280005,6825217,6208656
개인 할부구매 이용금액 (백만원),개인 할부구매 이용금액 (백만원),비은행계,3927300,4078874,4197182,4393728,4581085,4957799,4640116,4853368,...,6007471,5811446,6147608,5904367,5934717,6466482,5925795,5762330,6079422,5436922
개인 현금서비스 이용금액 (백만원),개인 현금서비스 이용금액 (백만원),합계,4822593,5006602,4362947,4492580,4426644,4440614,4486623,4353521,...,4900547,4748975,4730793,4920730,4917844,4972259,4948688,4945460,4632473,4473876
개인 현금서비스 이용금액 (백만원),개인 현금서비스 이용금액 (백만원),은행계,3151298,3277027,2844851,2934599,2889460,2899086,2904022,2816781,...,3142079,3036695,2994364,3155215,3172554,3222455,3243139,3240701,3053424,2935377
개인 현금서비스 이용금액 (백만원),개인 현금서비스 이용금액 (백만원),비은행계,1671295,1729575,1518096,1557981,1537184,1541528,1582600,1536740,...,1758467,1712280,1736429,1765515,1745290,1749804,1705549,1704759,1579050,1538498
법인 이용금액 (백만원),법인 이용금액 (백만원),합계,12230472,11001327,12220223,12765217,12362507,13678261,12662064,14579983,...,19854399,16523514,16401242,16111940,18461457,16989737,15312013,17909204,15006275,14582863
법인 이용금액 (백만원),법인 이용금액 (백만원),은행계,7599747,7375995,8399873,8667041,8111633,9852662,8713673,10064617,...,12561500,11165723,11309475,10828497,12609271,11585634,10705118,12704367,10620133,9618545
법인 이용금액 (백만원),법인 이용금액 (백만원),비은행계,4630725,3625332,3820350,4098176,4250874,3825598,3948390,4515366,...,7292900,5357792,5091768,5283443,5852185,5404102,4606895,5204837,4386142,4964318